/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AddBtn: typeof import('./src/components/AddBtn/index')['AddBtn']
  const AutoFontSize: typeof import('./src/components/AutoFontSize/index')['AutoFontSize']
  const Block: typeof import('./src/components/Block/index')['Block']
  const Card: typeof import('./src/components/Card/index')['Card']
  const Drawer: typeof import('./src/components/Drawer/index')['Drawer']
  const Ellipsis: typeof import('./src/components/Ellipsis/index')['Ellipsis']
  const FilterData: typeof import('./src/components/Filters/index')['FilterData']
  const Filters: typeof import('./src/components/Filters/index')['Filters']
  const FiltersProps: typeof import('./src/components/Filters/index')['FiltersProps']
  const Modal: typeof import('./src/components/Modal/index')['Modal']
  const PageLayout: typeof import('./src/components/PageLayout/index')['PageLayout']
  const PmAction: typeof import('./src/components/Permission/index')['PmAction']
  const PullRefresh: typeof import('./src/components/PullRefresh/index')['PullRefresh']
  const Select: typeof import('./src/components/Select/index')['Select']
  const Spin: typeof import('./src/components/Spin/index')['Spin']
  const Table: typeof import('./src/components/Table/index')['Table']
  const TablePage: typeof import('./src/components/TablePage/index')['TablePage']
  const TypeFormat: typeof import('./src/components/TypeFormat/index')['TypeFormat']
  const useTablePage: typeof import('./src/components/TablePage/index')['useTablePage']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { CardProps } from './src/components/Card/index'
  import('./src/components/Card/index')
  // @ts-ignore
  export type { TypeFormatProps } from './src/components/TypeFormat/index'
  import('./src/components/TypeFormat/index')
  // @ts-ignore
  export type { TableColumnData } from './src/components/Table/index'
  import('./src/components/Table/index')
  // @ts-ignore
  export type { FiltersProps, FilterData } from './src/components/Filters/index'
  import('./src/components/Filters/index')
  // @ts-ignore
  export type { EllipsisProps } from './src/components/Ellipsis/index'
  import('./src/components/Ellipsis/index')
}
