/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
    ACheckboxGroup: typeof import('@arco-design/web-vue')['CheckboxGroup']
    Action: typeof import('./src/components/Permission/Action.vue')['default']
    AddBtn: typeof import('./src/components/AddBtn/AddBtn.vue')['default']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    ALink: typeof import('@arco-design/web-vue')['Link']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    AutoFontSize: typeof import('./src/components/AutoFontSize/AutoFontSize.vue')['default']
    Block: typeof import('./src/components/Block/Block.vue')['default']
    Button: typeof import('./src/components/TablePage/Button.vue')['default']
    Card: typeof import('./src/components/Card/Card.vue')['default']
    Drawer: typeof import('./src/components/Drawer/Drawer.vue')['default']
    Ellipsis: typeof import('./src/components/Ellipsis/Ellipsis.vue')['default']
    Filters: typeof import('./src/components/Filters/Filters.vue')['default']
    Modal: typeof import('./src/components/Modal/Modal.vue')['default']
    PageLayout: typeof import('./src/components/PageLayout/PageLayout.vue')['default']
    PullRefresh: typeof import('./src/components/PullRefresh/PullRefresh.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Select/Select.vue')['default']
    Setting: typeof import('./src/components/TablePage/Setting.vue')['default']
    Spin: typeof import('./src/components/Spin/Spin.vue')['default']
    Table: typeof import('./src/components/Table/Table.vue')['default']
    TablePage: typeof import('./src/components/TablePage/TablePage.vue')['default']
    TypeFormat: typeof import('./src/components/TypeFormat/TypeFormat.vue')['default']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
  }
}
